name: Verify Commit

on:
  workflow_dispatch:
  push:
    branches:
      - production
  pull_request:
    branches:
      - production

defaults:
  run:
    shell: bash

jobs:
  lint_application:
    name: "Lint the Project"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.9" ]
        poetry-version: [ "1.4.0" ]
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Load cached Poetry installation
        uses: actions/cache@v2
        with:
          path: ~/.local
          key: poetry-0  # increment to reset cache

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: ${{ matrix.poetry-version }}
          virtualenvs-create: true
          virtualenvs-in-project: true

      - name: Load cached venv
        id: cached-poetry-dependencies
        uses: actions/cache@v2
        with:
          path: .venv
          key: venv-${{ runner.os }}-${{ steps.setup-python.outputs.python-version }}-${{ hashFiles('**/poetry.lock') }}

      - name: Install dependencies
        if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'
        run: |
          poetry install

      - name: Analyse the code with pylint
        run: |
          poetry run pylint $(git ls-files '*.py')

      - name: Analyse the code with flake8
        run: |
          poetry run flake8 $(git ls-files '*.py')

  test_application:
    name: "Test the Project"
    needs:
      - lint_application
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.8", "3.9", "3.10" ]
        poetry-version: [ "1.4.0" ]
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Load cached Poetry installation
        uses: actions/cache@v2
        with:
          path: ~/.local
          key: poetry-0  # increment to reset cache

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: ${{ matrix.poetry-version }}
          virtualenvs-create: true
          virtualenvs-in-project: true

      - name: Load cached venv
        id: cached-poetry-dependencies
        uses: actions/cache@v2
        with:
          path: .venv
          key: venv-${{ runner.os }}-${{ steps.setup-python.outputs.python-version }}-${{ hashFiles('**/poetry.lock') }}

      - name: Install dependencies
        if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'
        run: |
          poetry install

      - name: Run Unit Tests
        run: |
          poetry run python -m pytest

  build_and_run_image:
    name: "Build the Project as an Image and Run it as a Container"
    needs:
      - lint_application
      - test_application
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set Variables
        id: variables
        run: |
          echo "datetime=$(date +%Y%m%dT%H%M%SZ)" >> $GITHUB_OUTPUT
          echo "userid=$(id -u)" >> $GITHUB_OUTPUT
          echo "groupid=$(id -g)" >> $GITHUB_OUTPUT
          echo "${{ secrets.FIREBASE_SECRET }}" > $(pwd)/firebase_secret.json

      - name: Test Buildah Build
        run: |
          buildah bud \
          --file image/brvns.Containerfile \
          --tag ghcr.io/ziggiyzoo/brvns-discord-bot:gh-${{ steps.variables.outputs.datetime }} \
          .

      - name: Test Buildah Run
        env:
          TOKEN: ${{ secrets.DISCORDTOKEN }}
        run: |
          podman run \
          --env TOKEN=${{ secrets.DISCORDTOKEN }} \
          --volume $(pwd)/firebase_secret.json:/var/secrets/firebase_secret.json:ro \
          ghcr.io/ziggiyzoo/brvns-discord-bot:gh-${{ steps.variables.outputs.datetime }}

  run_application:
    name: "Run the Project"
    needs:
      - lint_application
      - test_application
    strategy:
      matrix:
        python-version: [ "3.8", "3.9", "3.10" ]
        poetry-version: [ "1.4.0" ]
        os: [ ubuntu-latest, windows-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3

      - name: Set Variables
        id: variables
        run: |
          echo "datetime=$(date +%Y%m%dT%H%M%SZ)" >> $GITHUB_OUTPUT
          echo "userid=$(id -u)" >> $GITHUB_OUTPUT
          echo "groupid=$(id -g)" >> $GITHUB_OUTPUT

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Load cached Poetry installation
        uses: actions/cache@v2
        with:
          path: ~/.local
          key: poetry-0  # increment to reset cache

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: ${{ matrix.poetry-version }}
          virtualenvs-create: true
          virtualenvs-in-project: true

      - name: Load cached venv
        id: cached-poetry-dependencies
        uses: actions/cache@v2
        with:
          path: .venv
          key: venv-${{ runner.os }}-${{ steps.setup-python.outputs.python-version }}-${{ hashFiles('**/poetry.lock') }}

      - name: Install dependencies
        if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'
        run: |
          poetry install

      - name: Run application
        env:
          TOKEN: ${{ secrets.DISCORDTOKEN }}
        timeout-minutes: 2
        continue-on-error: true
        run: |
          poetry run python main.py
